# Generated by Django 2.2.5 on 2021-12-18 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_auto_20211218_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderInfo',
            fields=[
                ('folderInfo_id', models.AutoField(primary_key=True, serialize=False, verbose_name='文件夹id')),
                ('update_time', models.DateTimeField(verbose_name='创建时间')),
                ('belong_folder', models.CharField(max_length=64, verbose_name='所属文件夹')),
                ('folder_name', models.CharField(max_length=64, verbose_name='文件夹名')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'db_table': '文件夹信息',
            },
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False, verbose_name='文件id')),
                ('file_path', models.CharField(max_length=128, verbose_name='存储路径')),
                ('file_name', models.CharField(max_length=128, verbose_name='文件名')),
                ('update_time', models.DateTimeField(verbose_name='上传时间')),
                ('file_type', models.CharField(max_length=32, verbose_name='文件类型')),
                ('file_size', models.CharField(max_length=16, verbose_name='文件大小')),
                ('belong_folder', models.CharField(max_length=64, verbose_name='所属文件夹')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'db_table': '文件信息',
            },
        ),
    ]
