# Generated by Django 2.2.5 on 2021-12-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fileinfo',
            table='文件',
        ),
        migrations.AlterModelTable(
            name='folderinfo',
            table='文件夹',
        ),
    ]
