# Generated by Django 2.2.5 on 2021-12-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20211221_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='update_time',
            field=models.CharField(max_length=30, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='folderinfo',
            name='update_time',
            field=models.CharField(max_length=30, verbose_name='上传时间'),
        ),
    ]
