# Generated by Django 2.2.5 on 2021-12-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20211221_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileinfo',
            old_name='file_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='folderinfo',
            old_name='folderInfo_id',
            new_name='id',
        ),
    ]
