# Generated by Django 2.2.5 on 2021-12-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_email',
            field=models.EmailField(max_length=254, verbose_name='客户邮箱'),
        ),
    ]
