# Generated by Django 2.2.5 on 2021-12-18 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20211216_1753'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='客户',
        ),
    ]
