# Generated by Django 2.2.5 on 2021-12-18 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='任务',
        ),
        migrations.AlterModelTable(
            name='taskadvise',
            table='任务审核',
        ),
        migrations.AlterModelTable(
            name='taskdistribution',
            table='任务分配',
        ),
    ]
