# Generated by Django 2.2.5 on 2021-12-22 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20211218_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskdistribution',
            old_name='task_distribution_endline',
            new_name='task_distribution_end_time',
        ),
    ]
