# Generated by Django 2.2.5 on 2021-12-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20211222_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_property',
            field=models.CharField(default='', max_length=20, verbose_name='任务性质'),
        ),
    ]
