# Generated by Django 2.2.5 on 2021-12-10 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False, verbose_name='工号')),
                ('name', models.CharField(default='', max_length=20, verbose_name='员工名字')),
                ('phone', models.CharField(default='', max_length=15, verbose_name='联系方式')),
                ('department', models.CharField(default='', max_length=30, verbose_name='部门')),
                ('job', models.CharField(default='员工（模型）', max_length=30, verbose_name='职务')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
