# Generated by Django 2.2.5 on 2021-12-16 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20211216_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffUsingSoftwareRecord',
            fields=[
                ('use_software_id', models.AutoField(primary_key=True, serialize=False, verbose_name='软件使用记录id')),
                ('software_name', models.CharField(default='', max_length=20, verbose_name='软件名字')),
                ('software_property', models.CharField(default='', max_length=20, verbose_name='软件性质')),
                ('use_software_begin_time', models.CharField(default='', max_length=20, verbose_name='软件使用开始时间')),
                ('use_software_end_time', models.CharField(default='', max_length=20, verbose_name='软件使用结束时间')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Staff')),
            ],
            options={
                'db_table': 'StaffUsingSoftwareRecord',
            },
        ),
    ]
