# Generated by Django 2.2.5 on 2021-12-18 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staffusingsoftwarerecord',
            table='员工使用软件记录',
        ),
    ]
