# Generated by Django 2.2.5 on 2021-12-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_auto_20211221_0924'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='software',
            table='软件',
        ),
    ]
